name: SivAndersson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74687
title: 'Siv Andersson – Poesi & Inspiration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aaa5c5'
    - '#fdf6d9'
    - '#7f7c8d'
    - '#1d283a'
    - '#c0a45b'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
