name: SivAndersson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74687
title: 'Siv Andersson – Poesi & Inspiration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eac7b4'
    - '#451900'
    - '#d39a89'
    - '#635d6b'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
