name: SivAndersson
favicon: null
layout_spectrum: 0.24024
typography_spectrum: 0.46792215667665005
title: 'Siv Andersson – Poesi & Inspiration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6dae3'
    - '#a19887'
    - '#767a83'
    - '#4c5457'
    - '#0b0604'
  brandStrength: 0.5
  lightness: 0.7190986047498882
  saturation: 0.24774108710698783
  rhythmicContrast: 0.75
purpose: []
